### ISSUE TITLE
Text To Speech support on Android

### ISSUE THREAD

**Issue by alexlarocca** [benbahrenburg/Utterance#4]
With module version 0.5, calling speech.isSupported() return false on my Samsung Galaxy Tab 3 (SM-T110), Android 4.2.2. 

Nevertheless text-to-speech works properly. Is there any risk ignoring isSupported return value? Could the module causes app crash on any device really not supporting this feature?

**Comment by benbahrenburg** [comment]
That is odd, isSupported just checks that the SDK version is greater than 18
~~~
return (Build.VERSION.SDK_INT > 18);
~~~

So technically if you are sure the SDK is at the proper level you can slip this check.

**Comment by alexlarocca** [comment]
Thanks Ben. So what is the minimum required SDK? Is it 19 (Android 4.3) like isSupported checks, or 14 (Android 4.0) as you wrote in the documentation?

**Comment by benbahrenburg** [comment]
For text to speech you should be ok with 4, for speech to text you will need 4.3
